---
name: Config Sync

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    uses: DevSecNinja/.github/.github/workflows/config-sync.yml@20bbfb951fc715ea1a30c6ed75032aa0acc0337e # v2.1.0
    permissions:
      contents: write
      pull-requests: write
