---
name: Config Sync

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    uses: DevSecNinja/.github/.github/workflows/config-sync.yml@ec116e82047d7d73abd678976b10325468d6fdd6 # v2.0.0
    permissions:
      contents: write
      pull-requests: write
